name: "CI for burger" 

on: [push] 

jobs:
  cooking: 
    runs-on: ubuntu-latest
    steps:
      - name: –î–æ—Å—Ç–∞—Ç—å –±—É–ª–æ—á–∫—É
        run: echo "ü•Ø –î–æ—Å—Ç–∞–µ–º –±—É–ª–æ—á–∫—É"

      - name: –ü–æ–∂–∞—Ä–∏—Ç—å –∫–æ—Ç–ª–µ—Ç—É
        run: echo "üçñ –ñ–∞—Ä—é –∫–æ—Ç–ª–µ—Ç—É 5 –º–∏–Ω—É—Ç"

      - name: –°–æ–±—Ä–∞—Ç—å –±—É—Ä–≥–µ—Ä
        run: echo 

  sale: 
    runs-on: ubuntu-latest
    steps:
      - name: –û—Ç–ø—Ä–∞–≤–∏—Ç—å –Ω–∞ –∫–∞—Å—Å—É
        run: echo "üõí –û—Ç–ø—Ä–∞–≤–∏—Ç—å –Ω–∞ –∫–∞—Å—Å—É"

      - name: –í—ã–¥–∞—Ç—å –±—É—Ä–≥–µ—Ä –∫–ª–∏–µ–Ω—Ç—É
        run: echo "ü§ù –í—ã–¥–∞—Ç—å –±—É—Ä–≥–µ—Ä –∫–ª–∏–µ–Ω—Ç—É"

      - name: –ü–æ–ª—É—á–∏—Ç—å –æ–ø–ª–∞—Ç—É
        run: echo "üí∞ –ü–æ–ª—É—á–∏—Ç—å –æ–ø–ª–∞—Ç—É"
